version: '3'

dotenv: ['.env']

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list

  click:
    desc: "Run OrderFlow CLI"
    silent: true
    cmds:
      - python3 src/orderflow/cli/main.py {{.ARGS}}

  service:
    desc: "Run Deribit FIX service"
    silent: true
    cmds:
      - python3 src/orderflow/cli/main.py service --config src/orderflow/cli/initiator.cfg

  clean:
    desc: "Clean logs and store files"
    cmds:
      - rm -rf log/ store/

  install:
    desc: "Install dependencies"
    cmds:
      - pip install quickfix click